### ISSUE TITLE
Allegro doesn't honor al_enable_menu_event_source for popup menus

### ISSUE THREAD

**Issue by oitofelix** [liballeg/allegro5#809] opened 2017-08-18 03:57 UTC
Events emitted for pop up menus always report being originated from the display's menu event source (field event.user.source) and its menu (field event.user.data3), irregardless of al_enable_menu_event_source calls.  This occurs even if the current display's menu is using its own menu event source rather than the default one.  This affects GTK and Windows.

**Comment by SiegeLord** [comment] 2017-08-27 19:53
The issue is not quite like that. I'm betting that you're reusing the id's between your main menu and your sub-menu. The way Allegro matches up what was clicked to the actual `ALLEGRO_MENU*` is by that id, which means that it will randomly find the display menu first (there's probably an array based on creation order or something). If you use a different id with your popup menu, it should work (at least, it did for me in the ex_menu example). Could you confirm that that is the case?

If so, in principle this is documented, but perhaps it may be possible to loosen this restriction somehow. A key sticking point is that on Windows, the code as is is forced to use the 16 bit integers, which exactly matches what Allegro API exposes as the id, but maybe we can come up with some idea for this.

If nothing else, we'll just document this better.

**Comment by oitofelix** [comment] 2017-08-27 20:33
> Could you confirm that that is the case?

Yes, that's it.

> The way Allegro matches up what was clicked to the actual ALLEGRO_MENU* is by that id, which means that it will randomly find the display menu first (there's probably an array based on creation order or something).

That being the case, I personally find the API for handling multiple menu sources far less useful than I had formerly presumed.

> If nothing else, we'll just document this better.

That would be nice.  Reading the documentation (carefully still), it wasn't clear at all to me that menu ids were conflated like that.  I had presumed that the purpose of multiple event sources was to have private scopes for ids.  In fact, priorly I had even thought that ids were privately scoped down to single menus.  That seems like the most natural behavior to me, and the documentation is (in my view) quite unclear in this regard.

**Comment by SiegeLord** [comment] 2017-08-27 21:01
> That being the case, I personally find the API for handling multiple menu sources far less useful than I had formerly presumed.

Yeah, I agree. It seems pointless to allow the flexibility of using a unique event source if it'll be randomly ignored.

Closing this in favor of #816.

**Closed by SiegeLord** 2017-08-27 21:01 UTC
Labels: Dialog addon
