### ISSUE TITLE
Support custom buttons for al_show_native_message_box on Windows

### ISSUE THREAD

**Issue by utz82** [liballeg/allegro5#821] opened 2017-09-11 12:43 UTC
As the title says. Custom buttons are currently not handled at all in the win_dialog implementation of _al_show_native_message_box, and are silently replaced by a single "OK" button. See https://github.com/liballeg/allegro5/blob/3bab6c6329ab458f351007674d08b2faba5bdc2b/addons/native_dialog/win_dialog.c#L283

**Comment by fatcerberus** [comment] 2017-09-11 13:22
This is a known issue, Windows doesn't have any way to put custom buttons in a system message box, so we'd have to author the dialog box ourselves.

**Comment by utz82** [comment] 2017-09-11 13:33
Then this should at least be documented, I think.
On the other hand creating custom forms on Win seems not so difficult, so I'd say it'd be worth the effort.

**Comment by fatcerberus** [comment] 2017-09-11 13:40
For some reason I thought it *was* documented, but I just checked and it's not.  Huh.

**Comment by utz82** [comment] 2017-09-11 16:08
Ok, I've changed the issue title so it can be used as a feature request. Feel free to close if this is an actual dupe now.

**Comment by SiegeLord** [comment] 2017-09-12 00:45
Yep, it's a duplicate of #386. At least needs to be documented.

**Closed by SiegeLord** 2017-09-12 00:45 UTC

**Comment by SiegeLord** [comment] 2017-09-12 00:49
Documentation changed commited in https://github.com/liballeg/allegro5/commit/94da47672c55ac484ded93380978a79115b7b25a
