### ISSUE TITLE
Mip Map regeneration

### ISSUE THREAD

**Issue by MarcDavenport** [liballeg/allegro5#934] opened 2018-10-07 01:25 UTC
Hiya, this is an oldie. When you draw to a texture, the mip maps don't get updated. There is a cheap workaround by calling al_clone_bitmap. An al_update_mipmap function might be nice to implement.

**Comment by SiegeLord** [comment] 2018-10-07 03:06
Duplicate of #559 :(.

**Closed by SiegeLord** 2018-10-07 03:06 UTC
