### ISSUE TITLE
Creating too-low sample rate mixer/voice crashes on exit

### ISSUE THREAD

**Issue by fatcerberus** [liballeg/allegro5#751] opened 2017-04-20 15:01 UTC
Repro code:
```c
ALLEGRO_VOICE* voice = al_create_voice(44, 16, ALLEGRO_CHANNEL_CONF_2);
ALLEGRO_MIXER* mixer = al_create_mixer(44, ALLEGRO_AUDIO_DEPTH_FLOAT32, ALLEGRO_CHANNEL_CONF_2);
al_attach_mixer_to_voice(mixer, voice);
al_set_voice_playing(voice, true);
al_set_mixer_playing(mixer, true);
al_destroy_mixer(mixer);
```

This leads to a segfault later upon calling `al_uininstall_audio()`

**Comment by tbass** [comment] 2017-04-20 20:42
I tried to reproduce it on an OSX system with the latest A5 HEAD and added a direct al_uninstall_audio() but did not get any segfaults. On OS do you run the code?

**Comment by fatcerberus** [comment] 2017-04-21 02:50
This is on Windows, for what it's worth.

**Comment by tbass** [comment] 2017-04-21 07:38
I tried to reproduce it on OSX and when calling ```al_uninstall_audio()``` directly after ```al_destroy_mixer()``` no segfault  happens, but when I do a lot of stuff inbetween and in my closing routine calling the ```al_uninstall_audio()``` routine I will also get a segfault.

**Comment by fatcerberus** [comment] 2017-04-21 13:38
Hm, sounds like a buffer overrun then.  The mixer is playing, so maybe the low sample rate causes it to eventually write past the end of the buffer sometimes.  I'll investigate.

**Closed** 2017-05-27 05:36 UTC
Labels: Audio addon, Crash

**Comment by SiegeLord** [comment] 2017-05-27 05:38
A few notes on the example itself beyond the commit message. `al_set_voice_playing` actually returns `false`, which means that something went wrong. You should be checking that return value and handling it in some way (granted it wouldn't prevent the crash, but now that the crash is gone what'll happen is that no sound will be played because `al_set_voice_playing` failed).

**Comment by fatcerberus** [comment] 2017-05-27 06:17
I didn't check the return value because I assumed that if `al_create_voice()` succeeded, then there would be nothing to prevent starting playback.  Now that I know that's not the case, I can update my own code accordingly to generate the proper error.

**Comment by fatcerberus** [comment] 2017-05-27 06:24
On a sidenote, you have no idea how often my users mistake the sample rate argument as kHz instead of Hz and try to pass `44.1` to the `Mixer` constructor.  I would have never discovered this bug in internal testing :p
