### ISSUE TITLE
Missing al_inhibit_screensaver implementation on X11

### ISSUE THREAD

**Issue by dos1** [liballeg/allegro5#995] opened 2019-02-03 04:52 UTC
Here's how SDL does it: https://hg.libsdl.org/SDL/file/1fc2169984ad/src/video/x11/SDL_x11events.c#l1464

**Comment by guilt** [comment] 2019-04-06 20:49
So we need X11_XScreenSaverSuspend and DBUS?

**Comment by rmbeer** [comment] 2019-05-01 16:50
I sent a new patch, it should work. I already tried it on my machine but it seems more like an X11 problem that does not stop the clock, it makes it blink for 1 second. If the problem is the same for all the machines, let me know, I have some ideas and I prefer to deepen it before commenting.

The Patch: #1045

**Comment by snoopdouglas** [comment] 2019-09-03 09:45
Just found this issue; #1078 merged, so guess we can close this now. @SiegeLord

**Comment by SiegeLord** [comment] 2019-09-03 15:09
Yep, thanks again!

**Closed by SiegeLord** 2019-09-03 15:09 UTC
Labels: Linux
